import { GameSession } from '../src/services/GameSession.js';
import { I18n } from '../src/services/I18n.js';
import { LOCALES } from '../src/data/locales.js';
import { BALANCE } from '../src/config.js';
import { ShareCardService } from '../src/services/ShareCardService.js';
import { AudioService } from '../src/services/AudioService.js';
import { requestLandscape, safePlayerSpawn } from '../src/utils/mobile.js';
import { GameUi } from '../src/ui/GameUi.js';
import { Hud } from '../src/ui/Hud.js';

const out=document.querySelector('#out');let passed=0,failed=0;
async function test(name,fn){try{await fn();out.textContent+=`PASS ${name}\n`;passed++;}catch(error){out.textContent+=`FAIL ${name}: ${error.message}\n`;failed++;}}
function assert(value,message='assertion failed'){if(!value)throw new Error(message);}

await test('all locales contain every English key',()=>{const keys=Object.keys(LOCALES.en);for(const [locale,data] of Object.entries(LOCALES))for(const key of keys)assert(key in data,`${locale}:${key}`);});
await test('session counts stages once per call',()=>{const s=new GameSession();s.recordKiosk('street');assert(s.destroyedTotal===1);assert(s.streetDestroyed===1);});
await test('weapon grants cap at double amount',()=>{const s=new GameSession();s.addWeapon('bat');s.addWeapon('bat');s.addWeapon('bat');assert(s.weapons.bat===BALANCE.caps.bat);});
await test('depleted weapon returns to fist',()=>{const s=new GameSession();s.addWeapon('shotgun');s.selectWeapon('shotgun');s.consumeWeapon('shotgun',99);assert(s.selectedWeapon==='fist');});
await test('empty weapon slots cannot be selected',()=>{const s=new GameSession();s.selectWeapon('bat');assert(s.selectedWeapon==='fist');});
await test('translation interpolation works',()=>{const s=new GameSession();const i=new I18n(s);assert(i.t('shareText',{count:4,time:'00:01.00'}).includes('4'));});
await test('all localized share templates interpolate',()=>{const s=new GameSession();const i=new I18n(s);for(const locale of Object.keys(LOCALES)){s.locale=locale;const text=i.t('shareText',{count:17,time:'00:03.21'});assert(text.includes('17'),locale);assert(text.includes('00:03.21'),locale);}});
await test('localized button labels fit their minimum widths',()=>{const canvas=document.createElement('canvas'),context=canvas.getContext('2d');const widths={language:430,guide:430,credits:430,start:440,back:220,retry:260,endless:300,share:250};for(const [locale,data] of Object.entries(LOCALES))for(const [key,width] of Object.entries(widths)){context.font='bold 28px Arial';const measured=context.measureText(data[key]).width;const fitted=measured>width-24?Math.max(16,Math.floor(28*(width-24)/measured)):28;context.font=`bold ${fitted}px Arial`;assert(context.measureText(data[key]).width<=width-18,`${locale}:${key}`);}});
await test('kiosk menu keeps game start inside guide',()=>{const s=new GameSession(),i=new I18n(s),ui=new GameUi(s,i);ui.showTitle({onLanguage(){},onGuide(){},onCredits(){}});assert(document.querySelectorAll('.service-list button').length===3);assert(![...document.querySelectorAll('.service-list button')].some(button=>button.textContent===i.t('start')));ui.showGuide({onStart(){},onBack(){}});assert([...document.querySelectorAll('button')].some(button=>button.textContent===i.t('start')));});
await test('language kiosk renders all ten choices',()=>{const s=new GameSession(),i=new I18n(s),ui=new GameUi(s,i);ui.showLanguage(Object.fromEntries(Object.keys(LOCALES).map(locale=>[locale,locale])),()=>{});assert(document.querySelectorAll('.language-button').length===10);});
await test('DOM HUD keeps four weapon slots and selected feedback',()=>{const s=new GameSession(),i=new I18n(s);s.addWeapon('bat');s.selectWeapon('bat');const hud=new Hud({},s,i,'targetStreet');hud.update('7 / 50');assert(document.querySelectorAll('.weapon-slot').length===4);assert(document.querySelector('.weapon-slot.selected')?.dataset.weapon==='bat');assert(document.querySelector('[data-hud="progress"]').textContent==='7 / 50');hud.destroy();});
await test('weapon pickup rasters load at 80x48',async()=>{for(const weapon of ['bat','chainsaw','shotgun']){const image=new Image();const loaded=new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;});image.src=`../assets/weapons/pickups/${weapon}.png`;await loaded;assert(image.naturalWidth===80&&image.naturalHeight===48,weapon);}});
await test('timer freezes after stop',()=>{const s=new GameSession();s.startTimer(100);s.stopTimer(350);assert(s.getElapsed(999)===250);});
await test('reset preserves chosen locale',()=>{const s=new GameSession();s.locale='pt-BR';s.recordKiosk();s.resetRun();assert(s.locale==='pt-BR');assert(s.destroyedTotal===0);});
await test('campaign balance uses 50 street kiosks',()=>assert(BALANCE.streetGoal===50));
await test('fist runs at the required 10 attacks per second',()=>assert(BALANCE.attack.fist.cooldown===100));
await test('fist destroys a kiosk in about one second',()=>{const duration=Math.ceil(BALANCE.kioskHp/BALANCE.attack.fist.damage)*BALANCE.attack.fist.cooldown;assert(duration>=800&&duration<=1100,String(duration));});
await test('factory fist time is within 35 to 45 seconds',()=>{const duration=Math.ceil(BALANCE.factoryHp/BALANCE.attack.fist.damage)*BALANCE.attack.fist.cooldown/1000;assert(duration>=35&&duration<=45,String(duration));});
await test('factory time stays in range with full weapon reserves',()=>{const batHits=BALANCE.caps.bat,shotgunHits=BALANCE.caps.shotgun,sawTicks=BALANCE.caps.chainsaw/BALANCE.attack.chainsaw.cooldown;const weaponDamage=batHits*BALANCE.attack.bat.factoryDamage+shotgunHits*BALANCE.attack.shotgun.factoryDamage+sawTicks*BALANCE.attack.chainsaw.factoryDamage;const weaponSeconds=(batHits*BALANCE.attack.bat.cooldown+shotgunHits*BALANCE.attack.shotgun.cooldown+BALANCE.caps.chainsaw)/1000;const fistSeconds=Math.max(0,BALANCE.factoryHp-weaponDamage)/(BALANCE.attack.fist.factoryDamage*1000/BALANCE.attack.fist.cooldown);const duration=weaponSeconds+fistSeconds;assert(duration>=35&&duration<=45,String(duration));});
await test('unmuting resumes requested music',()=>{const audio=new AudioService();let starts=0;audio.beginMusicLoop=()=>{starts++;};audio.startMusic();audio.toggleMute();audio.toggleMute();assert(starts===2,String(starts));});
await test('MIDI rock loop schedules layered cheap voices',async()=>{const audio=new AudioService();audio.context={};const voices=[];audio.tone=(frequency,duration,type)=>voices.push({frequency,duration,type});audio.beginMusicLoop();await new Promise(resolve=>setTimeout(resolve,250));audio.clearMusicTimer();assert(voices.length>=9,String(voices.length));assert(voices.some(voice=>voice.type==='square'));assert(voices.some(voice=>voice.type==='sawtooth'));assert(voices.some(voice=>voice.type==='sine'));});
await test('mobile landscape request succeeds when APIs exist',async()=>{let requested=false,mode='';const result=await requestLandscape({requestFullscreen:async()=>{requested=true;}},{lock:async value=>{mode=value;}});assert(requested&&mode==='landscape'&&result.fullscreen&&result.locked);});
await test('mobile landscape request falls back without throwing',async()=>{const missing=await requestLandscape({},{});const denied=await requestLandscape({requestFullscreen:async()=>{throw new Error('denied');}},{lock:async()=>{throw new Error('denied');}});assert(!missing.fullscreen&&!missing.locked&&!denied.fullscreen&&!denied.locked);});
await test('touch spawn clears the joystick footprint',()=>{assert(safePlayerSpawn(140,true)===230);assert(safePlayerSpawn(240,true)===240);assert(safePlayerSpawn(140,false)===140);});
await test('share card renders at 1080 square',()=>{const s=new GameSession();s.elapsedMs=12345;s.destroyedTotal=67;const card=new ShareCardService(s,new I18n(s)).createCanvas();assert(card.width===1080&&card.height===1080);});
await test('share card renders in all ten locales',()=>{const s=new GameSession();s.elapsedMs=12345;s.destroyedTotal=67;const i18n=new I18n(s);for(const locale of Object.keys(LOCALES)){s.locale=locale;const card=new ShareCardService(s,i18n).createCanvas();assert(card.width===1080&&card.height===1080,locale);}});
await test('share card uses the loaded strong character sprite',()=>{const source=document.createElement('canvas');source.width=27;source.height=24;const sourceContext=source.getContext('2d');sourceContext.fillStyle='#ff00ff';sourceContext.fillRect(0,0,27,24);const textures={get:key=>({getSourceImage:()=>key==='strong-attack'?source:null})};const s=new GameSession();const card=new ShareCardService(s,new I18n(s),textures).createCanvas();const pixel=card.getContext('2d').getImageData(160,400,1,1).data;assert(pixel[0]===255&&pixel[1]===0&&pixel[2]===255);});
await test('share card uses the loaded factory raster',()=>{const character=document.createElement('canvas');character.width=27;character.height=24;const factory=document.createElement('canvas');factory.width=1080;factory.height=640;const fc=factory.getContext('2d');fc.fillStyle='#00cc88';fc.fillRect(0,0,1080,640);const textures={get:key=>({getSourceImage:()=>key==='bg-factory'?factory:character})};const s=new GameSession();const card=new ShareCardService(s,new I18n(s),textures).createCanvas();const pixel=card.getContext('2d').getImageData(100,300,1,1).data;assert(pixel[0]===0&&pixel[1]===204&&pixel[2]===136);});
await test('share fallback creates a PNG download',async()=>{const original=HTMLAnchorElement.prototype.click;let clicked=0;HTMLAnchorElement.prototype.click=function(){clicked++;};try{const s=new GameSession();s.elapsedMs=12345;s.destroyedTotal=67;const service=new ShareCardService(s,new I18n(s));const outcome=await Promise.race([service.share(),new Promise(resolve=>setTimeout(()=>resolve('downloaded'),500))]);assert(outcome==='downloaded');assert(clicked===1);}finally{HTMLAnchorElement.prototype.click=original;}});
out.textContent+=`\n${passed} passed, ${failed} failed\n`;document.title=failed?'IHFK tests FAILED':'IHFK tests PASSED';
